name: 102 Static Website Deployment
on: 
  push:
    branches: [ main ]


jobs: 
  build-1:
    name: node install
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci

  build-2:
    name: GitHub Pipe
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Website
      run: 
        yarn
        npm run build
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Deploy to S3
      run: aws s3 sync public s3://${{ secrets.AWS_BUCKET_NAME }} --delete
    - name: Invalidate Cloudfront
      run: aws cloudfront creat-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"